# -*- coding: utf-8 -*-
"""TrustVerify CLI Tool

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_m_VZ1oXU0QWH08tv_u2SiPya7LbYRTc
"""

import hashlib
import json
import os
import argparse
import sys
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import rsa, padding
from cryptography.hazmat.primitives import serialization

# --- PART 1: Hashing and Local Integrity ---

def get_file_hash(filepath):
    """Task 1: Generates SHA-256 hash for a file (text, PDF, or image)."""
    sha256_hash = hashlib.sha256()
    try:
        with open(filepath, "rb") as f:
            for byte_block in iter(lambda: f.read(4096), b""):
                sha256_hash.update(byte_block)
        return sha256_hash.hexdigest()
    except Exception as e:
        print(f"Error hashing {filepath}: {e}")
        return None

def generate_manifest(directory=".", output_file="metadata.json"):
    """Task 2: Scans a directory and creates metadata.json with file hashes."""
    manifest = {}
    # Filter out script files and existing metadata to avoid circular hashing
    ignored_files = [output_file, "trust_verify.py", "private_key.pem", "public_key.pem", "signature.sig"]

    for filename in os.listdir(directory):
        filepath = os.path.join(directory, filename)
        if os.path.isfile(filepath) and filename not in ignored_files:
            file_hash = get_file_hash(filepath)
            if file_hash:
                manifest[filename] = file_hash

    with open(output_file, "w") as f:
        json.dump(manifest, f, indent=4)
    print(f"[+] Manifest created successfully: {output_file}")

def check_integrity(manifest_file="metadata.json"):
    """Task 3: Compares files against manifest to detect tampering."""
    if not os.path.exists(manifest_file):
        print(f"[-] Error: {manifest_file} not found. Run 'init' first.")
        return

    with open(manifest_file, "r") as f:
        manifest = json.load(f)

    print(f"[*] Verifying local integrity using {manifest_file}...")
    tampered = False
    for filename, original_hash in manifest.items():
        current_hash = get_file_hash(filename)

        if current_hash is None:
            print(f" [!] MISSING: {filename}")
            tampered = True
        elif current_hash != original_hash:
            print(f" [!] TAMPERED: {filename}")
            tampered = True
        else:
            print(f" [OK] {filename}")

    if not tampered:
        print("[+] SUCCESS: No unauthorized modifications detected.")
    else:
        print("[-] FAILURE: File integrity compromise detected!")

# --- PART 2: Digital Signatures (RSA) ---

def generate_keys():
    """Task 4: Generate RSA Public/Private key pair."""
    private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    public_key = private_key.public_key()

    # Save Private Key (PEM format)
    with open("private_key.pem", "wb") as f:
        f.write(private_key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption()
        ))

    # Save Public Key (PEM format)
    with open("public_key.pem", "wb") as f:
        f.write(public_key.public_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PublicFormat.SubjectPublicKeyInfo
        ))
    print("[+] RSA keys generated: private_key.pem and public_key.pem")

def sign_manifest(manifest_file="metadata.json", private_key_path="private_key.pem"):
    """Task 5: Signs the manifest file using the Private Key."""
    if not os.path.exists(manifest_file) or not os.path.exists(private_key_path):
        print("[-] Error: Manifest or Private Key missing.")
        return

    with open(private_key_path, "rb") as key_file:
        private_key = serialization.load_pem_private_key(key_file.read(), password=None)

    with open(manifest_file, "rb") as f:
        manifest_data = f.read()

    # Sign the data
    signature = private_key.sign(
        manifest_data,
        padding.PSS(mgf=padding.MGF1(hashes.SHA256()), salt_length=padding.PSS.MAX_LENGTH),
        hashes.SHA256()
    )

    with open("signature.sig", "wb") as f:
        f.write(signature)
    print("[+] Manifest signed. Signature saved as: signature.sig")

def verify_signature(manifest_file="metadata.json", public_key_path="public_key.pem", sig_path="signature.sig"):
    """Task 6: Verifies the manifest using the Public Key."""
    if not all(os.path.exists(f) for f in [manifest_file, public_key_path, sig_path]):
        print("[-] Error: Missing manifest, public key, or signature file.")
        return

    try:
        with open(public_key_path, "rb") as key_file:
            public_key = serialization.load_pem_public_key(key_file.read())

        with open(sig_path, "rb") as sig_file:
            signature = sig_file.read()

        with open(manifest_file, "rb") as f:
            manifest_data = f.read()

        public_key.verify(
            signature,
            manifest_data,
            padding.PSS(mgf=padding.MGF1(hashes.SHA256()), salt_length=padding.PSS.MAX_LENGTH),
            hashes.SHA256()
        )
        print("[+] VERIFICATION SUCCESS: The manifest is authentic and came from the trusted sender.")
    except Exception:
        print("[-] VERIFICATION FAILED: The manifest has been altered or the signature is invalid!")

# --- Main CLI ---

def main():
    parser = argparse.ArgumentParser(description="TrustVerify: CLI Tool for File Integrity & Digital Signatures")
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    subparsers.add_parser("init", help="Scan directory and create metadata.json")
    subparsers.add_parser("check", help="Verify local file integrity against manifest")
    subparsers.add_parser("keys", help="Generate RSA public/private key pair")
    subparsers.add_parser("sign", help="Sign the manifest file with private key")
    subparsers.add_parser("verify", help="Verify manifest authenticity with public key")

    args = parser.parse_args()

    if args.command == "init": generate_manifest()
    elif args.command == "check": check_integrity()
    elif args.command == "keys": generate_keys()
    elif args.command == "sign": sign_manifest()
    elif args.command == "verify": verify_signature()
    else: parser.print_help()

if __name__ == "__main__":
    main()